[package]
name = "day-1"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "day-1"
path = "src/bin/part-1.rs"

[[bin]]
name = "day-1b"
path = "src/bin/part-2.rs"

[dependencies]
